### ISSUE TITLE
Theme dark du site https://conso.boris.sh/

### ISSUE THREAD

**Issue by mnegorth** [bokub/conso-api#1]
Bonjour,
sur le nouveau site https://conso.boris.sh/ le texte s'affiche en blanc sur fond blanc . Rien de bien bloquant mais étonnant au premier coup d'œil :-)

**Comment by bokub** [comment]
Effectivement, je n'utilise pas le thème sombre et je n'avais donc jamais remarqué

Je ferai une correction la semaine prochaine

**Comment by bokub** [comment]
Hello,

Le problème devrait être corrigé, le site devrait rester 100% en mode "clair" même si ton système est en mode sombre
