### ISSUE TITLE
Appel bloqué par cloudflare

### ISSUE THREAD

**Issue by codavs65r** [bokub/conso-api#12]
Bonjour,
Depuis aujourd'hui mes appel tombent en erreur. J'aurais été bloqué.
Ci-dessous le CoudFlare Ray ID : 
8115bf4c0f9d2a07

J'ai bien ajouté un user agent dans le header de mes appels mais ça ne change rien.

Merci pour ton aide.

Cordialement,
Nicolas.

**Comment by codavs65r** [comment]
Bon, désolé, mes headers étaient mal paramétré. Ca remarche après ma correction.

**Comment by bokub** [comment]
Hello,
J'étais en train de coder un script pour bloquer automatiquement les gens qui abusent, j'ai fait quelques essais avec une limite très basse juste pour tester que tout marchait bien, et il y a bien eu des blocages qui ont duré quelques minutes mais si tu n'a pas spammé l'API tu devrais avoir été débloqué

Bonne journée

**Comment by codavs65r** [comment]
Salut,
Bon finalement ca bloque encore.
J'ai mis en place un cache de mon coté pour ne faire que que quelques appels par jour.
Id cloudflare : 81161564ab4022ab
Encore désolé.
Merci pour ton aide.
Cordialement,
Nicolas.

**Comment by bokub** [comment]
Est-ce que tu reconnais ton IP ou non ? 

![image](https://github.com/bokub/conso-api/assets/17952318/da6f45d7-c8d6-4a61-b627-cf9ae53a8e14)

**Comment by codavs65r** [comment]
Effectivement c'est ça. Le nombre de requête a l'air cohérent aussi.
Merci.

**Comment by bokub** [comment]
> J'ai mis en place un cache de mon coté pour ne faire que que quelques appels par jour.

Tu veux dire que tu viens de mettre un cache en place ? Ou qu'il était déjà là avant ?

Parce que là quand je vois que tu fais exactement la même requête plusieurs dizaines de fois dans la même journée, voire plusieurs fois dans la même minute, je me dis que le ban est amplement mérité

**Comment by bokub** [comment]
OK, j'ai retiré ton IP de la blacklist !
Bonne journée

**Comment by codavs65r** [comment]
Merci beaucoup. Bonne journée.
