### ISSUE TITLE
Blacklist

### ISSUE THREAD

**Issue by neoworld7** [bokub/conso-api#14]
Bjr
J’utilise votre API par le biais d’un plugin homebridge (linky meter)

J’ai configuré le système et mon adresse IP c’est faite blacklisté de votre API… :(

**Comment by bokub** [comment]
Salut,
Tu peux me donner les premiers caractères de ton IP s'il te plaît afin que je puisse la retrouver ?

**Comment by neoworld7** [comment]
Re,
86.218.3X

J’ai désactivé le plugin; et je vais faire attention aux réglages. J’étais resté en standard.

Le plugin homebridge est celui la: https://github.com/tthma/homebridge-linky-enedis-meter

**Comment by neoworld7** [comment]
Merci

**Comment by bokub** [comment]
Effectivement, ton IP a été bloquée automatiquement car elle a été à l'origine de **135 requêtes** dans un intervalle de **12 heures** le 22 octobre.

Comme indiqué clairement sur https://conso.boris.sh, faire plus d'**une requête** par jour est **strictement inutile** car les données ne remontent qu'**une fois par jour**.

Le plugin que tu utilises a fait 135 fois trop de requêtes juste entre minuit et midi, c'est du pur gaspillage de ressources à la fois de ton côté et du mien.

Je débloque ton IP mais en échange ce serait sympa de ta part de demander à l'auteur du plugin de faire un correctif pour éviter ce genre de problème. Je met mon serveur à disposition de tous, gratuitement et sans rien demander en retour, mais ce n'est pas viable si les utilisateurs du service ne font aucun effort pour l'utiliser de façon responsable.

Merci d'avance et bonne journée

**Comment by neoworld7** [comment]
Merci, je regarde comment bien paramétrer avant de relancer.

De ce que j’ai vu. Le plugin lançait les récupérations de 7 jours par 7 jours. D’où le gros volume.

**Comment by neoworld7** [comment]
Voici ce qu’il se passe qd on lance le plugin; avec une date d’historique au 01/10/23




[27/10/2023, 14:50:26] [Linky Meter] Query start = 2023-10-01 End = 2023-10-08
[27/10/2023, 14:50:29] [Linky Meter] Query 2023-10-01/2023-10-08 Finish

[27/10/2023, 14:51:26] [Linky Meter] Query start = 2023-10-08 End = 2023-10-15
[27/10/2023, 14:51:31] [Linky Meter] Query 2023-10-08/2023-10-15 Finish
 
[27/10/2023, 14:52:26] [Linky Meter] Query start = 2023-10-15 End = 2023-10-22
[27/10/2023, 14:52:35] [Linky Meter] Query 2023-10-15/2023-10-22 Finish
 
[27/10/2023, 14:53:26] [Linky Meter] Query start = 2023-10-22 End = 2023-10-27
[27/10/2023, 14:53:33] [Linky Meter] Query 2023-10-22/2023-10-27 Finish

**Comment by bokub** [comment]
Je compte pas le volume mais le nombre de requêtes. Dans ton exemple ça fait seulement 4 requêtes pour 4 semaines de données donc on est très loin des 135 requêtes

**Comment by neoworld7** [comment]
Je pense que le plugin c’est emballé la dernière fois.

**Comment by bokub** [comment]
T'es sûr qu'il fait pas la même requête plein de fois au cours de la journée ?

J'y connais rien je comprends même pas à quoi il sert ce plug-in mais ça pourrait être une explication

Maintenant que j'ai ton IP je regarderai les requêtes qui passent pendant la journée une fois que tu auras rallumé ton plug-in

**Comment by neoworld7** [comment]
Le plugin sert à rapatrier les données linky dans homebridge pour les lire dans HomeKit (application Ève) et ainsi avoir le suivi de linky.

J’ai relancé le plugin en ne demandant que les données depuis le 01/10; cela a lancé les 4 requêtes..

**Comment by bokub** [comment]
Bon, ton IP fait une seule requête par jour depuis 3 jours, je considère que le problème est résolu et je ferme l'issue

Bonne journée !

**Comment by neoworld7** [comment]
Bonjour,
Merci, heureux que ce soit résolu  !
