### ISSUE TITLE
Page vierge lors de la création du token

### ISSUE THREAD

**Issue by TrollDiplomate** [bokub/conso-api#17]
Bonjour,

Merci pour ce travail !

Lorsque je clique sur le bouton "J'accède à mon espace client Enedis" je tombe sur une page Enedis vierge à part "Partage de vos données d’électricité" indiqué en haut de page.
J'ai bien un compte Enedis sur lequel je suis déjà loggué et dans lequel j'ai activé le partage de données.

Merci pour votre aide,

**Comment by MrBLJ** [comment]
Même constat. Essai avec plusieurs navigateurs (frifox, brave, edge), toutes les extensions désactivées.

**Comment by bokub** [comment]
Hello, si le problème est sur la page de consentement, il s'agit un souci côté Enedis et je n'ai malheureusement pas la main dessus.

Pour info, j'avais le même problème hier et aujourd'hui, mais je viens de réessayer à l'instant et j'ai eu un token. Vous pouvez réessayer ?

**Comment by TrollDiplomate** [comment]
> Hello, si le problème est sur la page de consentement, il s'agit un souci côté Enedis et je n'ai malheureusement pas la main dessus.
> 
> Pour info, j'avais le même problème hier et aujourd'hui, mais je viens de réessayer à l'instant et j'ai eu un token. Vous pouvez réessayer ?

Bonjour Boris,
Merci pour ton retour !
Je viens de tenter et effectivement ça a marché du premier coup.

Excellente journée a toi

**Comment by bokub** [comment]
Hello, c'est peut-être pas 100% réparé par Enedis, ils sont souvent longs, je t'invite à attendre encore un jour où deux et à réessayer.
En attendant, vérifie que tu as accès à tes donnés (y compris par demi-heure) sur ton espace client Enedis !

**Comment by bokub** [comment]
J'ai effectivement le même problème que toi, à la fois sur Conso API et sur d'autres services, donc la page de consentement est encore cassée :cry:

**Comment by ilyadel** [comment]
Bonjour, 
ça semble de "nouveau" d'actualité, j'ai également l'erreur "Compteur incompatible", j'ai essayé plusieurs fois depuis hier.
Je viens de créer un compte sur le service "Lite" , ils ont bien réussi à avoir le consentement, je vois bien 2 nouveaux contrats au niveau des "Partage des données". 
Ils utilisent peut être d'autres méthodes pour le consentement ?

**Comment by MrBLJ** [comment]
> > @bokubca m'a effectivement l'air d'être lié au site Enedis. La page se charge désormais. Manque de pot, mon compteur est incompatible (allez savoir pourquoi) : Evidemment, rien n'est listé au dessus. ![image](https://user-images.githubusercontent.com/12542442/282541152-0cf66e40-53c2-4751-adb0-f009404bf296.png)
> > J'utilise actuellement MyEletricalData pour le relevé de mes mesures, c'est tout juste fonctionnel et je souhaitais changer. Je vais poncer la doc.
> 
> J'ai exactement le même problème "compteur incompatible" Est ce que cela a été résolue chez vous?

Je viens de tenter de nouveau : même résultat. Je patiente en espérant un miracle côté Enedis.

**Comment by emylive** [comment]
Ca viens de fonctionner pour moi et mes 2 PDL!!!
Merci beaucoup pour ce super service!

**Comment by ilyadel** [comment]
OK de mon côté également (il y a 15min)
Merci pour l'énorme travail.

**Comment by GaboFlo** [comment]
J'ai le même problème, sur deux comptes différents (deux PDL différents aussi) dont un pour lequel j'ai déjà un token, toujours fonctionnel, mais je ne peux pas m'en régénérer un autre 😵‍💫

**Comment by BoD** [comment]
Voilà j'imagine bien que ça ne sert pas à grand chose de le dire, mais sachez que j'ai le même soucis :(  Moi qui voulait coder un truc sympa ce week-end :(

**Comment by BoD** [comment]
Cela ne fonctionne toujours pas pour moi. 

@bokub étant donné que vous avez un contrat avec Enedis, n'avez-vous pas un canal pour demander du support ou ouvrir une issue sur leur API? Désolé d'insister mais si cette page ne fonctionne pas, ce projet ne peut tout simplement pas être utilisé, et c'est bien dommage.

**Comment by bokub** [comment]
@BoD Pour le problème de "compteur incompatible" ça se passe ici: #26

**Comment by petervandepol** [comment]
Rien de succes pour moi aussi....
