### ISSUE TITLE
Probleme de creation du token

### ISSUE THREAD

**Issue by Kalltech** [bokub/conso-api#18]
Hello,

Je clique sur le lien https://conso.boris.sh/api/auth puis j'arrive sur la page pour selectionner le compteur mais apparement il est incompatible.
![Sans titre](https://github.com/bokub/conso-api/assets/7604214/d2a10a61-9711-47d8-9e4e-b8ab54327c45)
Y a t il une solution?

Merci et beau boulot pour cette integration!
Steve

**Comment by bokub** [comment]
Hello !
Même problème que #17, je t'invite à aller voir là bas
