### ISSUE TITLE
Réponse KO différente de OK

### ISSUE THREAD

**Issue by fsneew** [bokub/conso-api#20]
Si la réponse est KO, on a  {"status":401,"message":"Votre token est invalide ou ne permet pas d'accéder à ce PRM"}

Si c'est OK on a {"usage_point_id":"XXX","start":"2023-08-19","end":"2023-08-20","quality":"BRUT","reading_type":{"unit":"Wh","measurement_kind":"energy","aggregate":"sum","measuring_period":"P1D"},"interval_reading":[{"value":"6881","date":"2023-08-19"},{"value":"7869","date":"2023-08-20"}]}

Je m'attendais à avoir un status 200 dans le second cas. Est-ce normal ? Merci :-)

**Comment by fsneew** [comment]
Salut @bokub !

OK je comprends mais c'est juste que l'on peut pas dire de tester status dans tous les cas.

**Comment by bokub** [comment]
En effet, tu devrais toujours regarder le code de retour HTTP ! 

Le status dans la réponse est "complémentaire" et sert uniquement à faciliter la vie (par exemple pour mieux comprendre l'erreur sur la page https://conso.boris.sh/examples )
