### ISSUE TITLE
Linky Conso Hourly

### ISSUE THREAD

**Issue by dawaman88** [bokub/conso-api#23]
Hello,

Is it possible to use your API and have the hourly consumption?

Thanks a lot

**Comment by bokub** [comment]
Hello,

Yes, you need to use the `/consumption_load_curve` path 

```
https://conso.boris.sh/api/consumption_load_curve?prm=123456&start=2023-12-01&end=2023-12-20
```

**Comment by dawaman** [comment]
> Hello,
> 
> Yes, you need to use the `/consumption_load_curve` path
> 
> ```
> https://conso.boris.sh/api/consumption_load_curve?prm=123456&start=2023-12-01&end=2023-12-20
> ```

and for production hourly ?

**Comment by bokub** [comment]
`production_load_curve`. 

Full documentation is available here (in french): https://conso.boris.sh/documentation

**Comment by dawaman88** [comment]
Perfect thanks a lot

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
