### ISSUE TITLE
Cloudflare blocked

### ISSUE THREAD

**Issue by pierick** [bokub/conso-api#25]
Bonjour,

je me permet de reposter ici ma demande de déblocage / Ban Cloudlare,
en effet, j'avais ajouté ma demande dans un post précédent : https://github.com/bokub/conso-api/issues/21
mais je suis sans réponse depuis le 13 décembre.

je ne connais pas les circonstance exactes de mon blocage, mais je pense que j'ai eu un probleme avec un redémarrage sans fin de node red pendant quelques heures autour de fin novembre ou début décembre.

j'avais paramétré le noeud linky pour se déclencher une fois par jour a 4h du matin.

___

**Pouvez-vous me débloquer, s'il vous plaît ?** 

Mon adresse IP visible depuis la page https://conso.boris.sh/ est la suivante :
Cloudflare Ray ID : 834ffab0c8f202c9
Votre IP : 2a01:e0a:xxx:xxx:xxx:xxx:a6fb:43f0
IP publique : 82.64.2xx.xxx

(Je masque partiellement l'IP car ce message est public.)

Par avance, merci.

**Comment by bokub** [comment]
Salut @pierick ,

Si je comprends bien, tu me demandes de débloquer ton IP qui fait des appels en boucle à mon serveur, alors que tu n'as pas clairement identifié la source de ton problème, et que tu n'as rien mis en place pour éviter que ça ne se reproduise. C'est bien ça ?

P.S: Il me faudrait les caractères sous les 3 premiers `x` car il y a trop d'IPs qui commencent comme la tienne (et je ne peux pas voir la fin des adresses IPv6 bloquées, j'utilise un masque) - 2a01:e0a:**xxx**

**Comment by bokub** [comment]
Ah, je viens de retrouver ton adresse IP grâce au message que tu avais mis dans l'issue #21 

Ton IP a fait 1221 appels API en seulement 12 heures ! Félicitations, tu es sur le podium des plus gros spammeurs de mon serveur 😭

**Comment by pierick** [comment]
Bonjour,

merci beaucoup pour votre action.

j'utilisais dans Node-Red le noeud "Inject" pour les tests avec un mode repeat 
c'est probablement un mauvais paramétrage de ce noeud qui a causé le probleme.

Ce que j'ai remarqué, c'est qu'une fois le ban actif, cela fait planter le noeud Linky, et c'est l'ensemble du service Node-Red qui crash.

Dans tous les cas, je suis revenu à une utilisation plus standard avec un noeud de type "Crontab" et un seul déclenchement journalier.

désolé pour la perturbation.

**Comment by bokub** [comment]
OK ça devrait être débloqué maintenant, tu peux confirmer ?

**Comment by pierick** [comment]
je confirme, c'est bon.

Merci beaucoup
