### ISSUE TITLE
Compteur incompatible

### ISSUE THREAD

**Issue by pescap** [bokub/conso-api#26]
Bonjour, j'essayais de générer un token et mon compteur m'apparait comme incompatible:

<img width="712" alt="Screenshot 2023-12-29 at 12 10 12" src="https://github.com/bokub/conso-api/assets/14826266/9b436f1d-8ea3-46ba-91be-fe3dfaeaf5ac">

Avez-vous une idée de la cause de cette erreur?
Merci pour votre précieuse aide

**Comment by bokub** [comment]
Hello,

Le problème vient de la page de consentement, il s'agit donc un souci côté Enedis et je n'ai malheureusement pas la main dessus.

Je t'invite à patienter quelques jours, ça avait suffit pour #17

Bonne journée !

**Comment by agaget** [comment]
Hello,
Pour info j'ai le même souci de compteur incompatible, j'ai fais un message à Enedis pour les relancer. J'attends également.

**Comment by bokub** [comment]
J'ai également envoyé un e-mail à Enedis, en espérant qu'ils se bougent rapidement en ce début d'année

**Comment by pescap** [comment]
Bonjour, merci pour vos retours! Pas de changement de mon côté hélas!

**Comment by abesnier** [comment]
J'ai la même chose, je me permets juste de répondre à cette issue pour recevoir une notification de Github si quelqu'un répond que c'est réparé côté Enedis!

**Comment by bokub** [comment]
Pour les suivants qui voudraient faire pareil, il y a aussi ce bouton sur la droite qui permet de faire exactement la même chose **sans** envoyer une notifications à tous les participants :wink: 

![image](https://github.com/bokub/conso-api/assets/17952318/8801084f-db10-4c8b-bd88-50d3600b68d8)

**Comment by Spl4sh57** [comment]
Pareil ticket ouvert pour ma part... plus qu'à attendre :)

**Comment by hub2rock** [comment]
Hello,
Idem ticket ouvert chez eux. En espérant que si nous sommes plusieurs cela fasse bouger les choses. Je vous tiendrais au courant sur ce thread si j'ai une réponse ou si ca marche à nouveau.
Merci.

**Comment by bokub** [comment]
Hello,

Enedis m'a envoyé un e-mail pour me prévenir qu'ils ont bien détecté un problème (enfin !), et qu'il devraient le corriger le 25 janvier !
On croise les doigts :crossed_fingers:

**Comment by killkuter** [comment]
Cool, merci pour les infos. Je suis dans le même cas que vous.

**Comment by didi4yeah** [comment]
Moi aussi mince.
J'ai voulu faire ça hier mais bloqué à cette étape aussi :s
Merci pour les info de mise à jour.
J'espère que ça vraiment se débloquer dans quelques jours :p

**Comment by niko44** [comment]
ah ! on croise les doigts pour que demain tout remarche !

**Comment by Gabin85** [comment]
Pour l'instant toujours pareil, après la journée n'est pas terminé

**Comment by MPoivre31** [comment]
On va tabler sur le 25 janvier révolu ? 🥲

**Comment by bokub** [comment]
Sans grande surprise, la date butoir du 25 janvier est passée et le problème subsiste

J'ai contacté Enedis à nouveau pour leur signaler, car les connaissant ils n'ont pas dû s'en rendre compte (à moins qu'il soient juste en retard sur leur correctif ?)

**Comment by BoD** [comment]
(Pardon d'avoir commenté sur la mauvaise issue auparavant) 

Merci beaucoup d'avoir contacté et relancé Enedis, et donc ... patience pour l'instant. Je me suis abonné à cette issue :)

**Comment by killkuter** [comment]
Effectivement ça ne fonctionne toujours pas, merci pour la relance.
Croisons les doigts ...
Bonne journée à tous

**Comment by domocip** [comment]
Salut
Toujours NOK chez Enedis... C'est fou. J'ai envoyé une demande.
Merci pour le travail en tout cas. ;-)

**Comment by domocip** [comment]
MAJ : En revanche j'ai l'impression que la demande de consentement pour "Myelectricaldata" fonctionne, je n'ai pas d'alerte vis à vis de mon compteur.
N'y aurait il pas une vérification du nombre de consentements accordés ou autre vérifs afin que cela ne soit pas "industrialisés" ?
https://www.myelectricaldata.fr/documentation

**Comment by bokub** [comment]
Non mais cherche pas trop loin, c'est pas un problème avec ton compteur ou une vérification quelconque sur les consentements...

La raison du problème, d'après eux, c'est juste que la dernière fois que j'ai modifié des détails de mon application sur mon dashboard développeur Enedis, leur service était à moitié en rade et a complètement pété les données de mon application dans leur base de données.

C'est pour ça que tu ne peux voir ni le logo de mon application (orange), ni son nom (rouge).

![image](https://github.com/bokub/conso-api/assets/17952318/8f06f4d2-7ca2-44f7-af4e-1507ba7dfa3f)

C'est aussi pour ça que les autres services similaires ne sont pas cassés

Pourquoi c'est si long à réparer ? Parce que c'est Enedis, tout simplement 🙃

**Comment by bokub** [comment]
Pour vous tenir au courant:

> Nous sommes navrés, mais le correctif attendu est repoussé au 31/01, au mieux.
> Nous vous présentons nos excuses pour la gêne occasionnée, et restons à votre écoute

Quelle surprise

**Comment by BoD** [comment]
le "au mieux" est amusant 😅

**Comment by niko44** [comment]
C'est bon ça remarche!!!!

**Comment by BoD** [comment]
Je confirme ! 🎉

**Comment by killkuter** [comment]
chez moi non c'est toujours le même problème même en testant avec une navigation privée histoire d'être sûr du cache ...

**Comment by phid78** [comment]
GO GO GO ca fonctionne ;)

**Comment by killkuter** [comment]
C'est bon ça fonctionne cette fois-ci. Merci

**Comment by hub2rock** [comment]
Hello,

Vous aussi vous avez ce message d'erreur maintenant :

![image](https://github.com/bokub/conso-api/assets/2854830/47bec1ce-71cc-4996-b72d-bf0e2a560179)

**Comment by killkuter** [comment]
Oui normal je crois que c'est tous les débuts de mois comme ça.

**Comment by pescap** [comment]
Bonjour, de mon côté j'ai cela:
<img width="1309" alt="Screenshot 2024-02-06 at 09 29 20" src="https://github.com/bokub/conso-api/assets/14826266/d293caf1-c57a-4ae5-b97e-2e3cc7276a17">

**Comment by bokub** [comment]
Y'a quelques message d'excuses sur leur Twitter

https://twitter.com/enedis_clients/with_replies

![image](https://github.com/bokub/conso-api/assets/17952318/67f0c4cb-e9a9-4f22-8f3c-c84d4c92a7b6)

**Comment by niko44** [comment]
C'est véritablement une calamité la maintenance de ce site. Certes ce n'est pas un site à caractère vital pour la nation, mais cela indique clairement le niveau de compétences des personnes assurant la maintenance... Et le pire dans tout ça c'est que les applications clientes comme celle de @bokub sont directement impactées voire pire on pense directement que c'est elle le pb alors que non!

**Comment by bokub** [comment]
Je te confirme que ça fait chier d'avoir mis en place un service avec un uptime de 99.9% depuis des années, mais de dépendre d'un service grassement payé par nos impôts qui peine à régler un incident en moins d'une semaine... :cry: 

Et je te confirme aussi qu'une bonne partie des issues ouvertes sur [conso-api](https://github.com/bokub/conso-api), [linky](https://github.com/bokub/linky), ou encore [ha-linky](https://github.com/bokub/ha-linky) vient de problèmes d'Enedis. Parfois on me contacte sur mon site personnel ou sur mon LinkedIn pour me demander de l'aide, c'est assez intrusif en plus d'être pénible. Des fois je me demande pourquoi je me suis embarqué dans des projets pareils...

**Comment by BoD** [comment]
Merci @bokub d'avoir créé ce service ! Honnêtement c'est une honte que son existence soit nécessaire - pourquoi l'API d'Enedis nécessite d'être une entreprise ? Et le fait qu'elle soit si instable est inadmissible.

En fin de compte personnellement j'ai fini par faire du scraping (via [Playwright](https://playwright.dev/)) sur le site d'EDF pour mon petit projet perso. Mais c'est pareil, j'aurais préféré qu'ils proposent une API, ce sont MES données après tout. L'avantage c'est qu'on a aussi la consommation en euros.

Je ne dis pas ça pour décourager les gens d'utiliser ce projet, mais juste pour donner une perspective d'alternative.

**Comment by bokub** [comment]
Hello à tous, le don de consentement est à nouveau fonctionnel :partying_face: 

Bonne journée !

**Comment by GilDev** [comment]
Et la connexion à l’espace client !

Ils avaient parlé du 12 février, finalement ils ont corrigé le souci plus tôt que prévu… 🤔 Je surveille la météo…

**Comment by NicolasLambert** [comment]
Le problème est revenu 😭

**Comment by Gabin85** [comment]
Oui depuis 1 mois mais si t’as tjr ta clé d’API ça fonctionne toujours

**Comment by NicolasLambert** [comment]
Hélas non je suis un nouvel utilisateur

**Comment by bokub** [comment]
👉 #62 👈
