### ISSUE TITLE
Enedis : "Site fermé temporairement  pour maintenance"

### ISSUE THREAD

**Issue by tanguyblack** [bokub/conso-api#28]
Bonjour,
J'essaye depuis quelques jours  pour ajouter mon compteur linky dans mon ha 
en allant sur le bouton 
"j'accede a mon espace enedis "
j'arrive sur la page avec le message suivant 
"Site fermé temporairement
pour maintenance"

Est ce connu / Contournement possible  / autre solution ? 

Merci d'avance de toute aide 
Tanguy

**Comment by bokub** [comment]
Hello @tanguyblack !

> Est ce connu 

On dirait que oui: https://twitter.com/enedis_clients/with_replies

> Contournement possible / autre solution ?

Non désolé, je bosse pas chez Enedis et je suis pas magicien, si leur site dit qu'il est "fermé" et "en maintenance" c'est qu'il est fermé et en maintenance, je comprends pas à quoi tu t'attendais comme réponse :shrug: 

Bonne journée

**Comment by tanguyblack** [comment]
Désolé je ne voulais pas dire "c'est pas normal ca marche pas" 
mais si pour les autres ca marchent et que j'ai peut etre un probleme lié a chez moi 
( navigateur, cookies ou autres chez moi ) 
donc il suffit que je m'arme de patience qu'enedis remette en route son systeme 

donc toutes mes excuses encore si mon message laissait a penser que j'exigeais quelque chose 
je ne peux que être reconnaissant d'un travail fourni gratuitement  

Pour info Enedis a évolué maintenant j'ai "Compte client particulier indisponible"   :) :)

**Comment by bokub** [comment]
Salut @tanguyblack !

Le problème a l'air résolu, j'ai réussi à générer un token à l'instant :partying_face: 

Désolé si ma réponse t'a paru un peu sèche sur le moment, c'est juste que je me fais assaillir de messages en tout genre à chaque fois que le site d'Enedis est down alors qu'il n'y a littéralement rien que je puisse faire. Le fait que le don de consentement n'ait été fonctionnel que 2 jours depuis le début d'année n'aide pas.

Bonne journée !

**Comment by tanguyblack** [comment]
Cool merci de cette bonne nouvelle 
Pas de souci pour ta réponse et j'imagine bien le nombre de gens qui doivent "exiger "de toi que ca fonctionne 
je travaille aussi dans l'informatique et récemment je me suis fait eng...lé parce qu'il n'y avait plus de courant et que je n'avais pas de solution :) 
Merci je vais tester ca ce week end ( si enedis tient jusque la :)
