### ISSUE TITLE
Ce token ne permet pas d'accéder au PRM

### ISSUE THREAD

**Issue by JNoVernay** [bokub/conso-api#35]
Bonjour, merci pour cette API prometteuse pour mon intégration et le travail derrière. Mais depuis hier, ou j'ai initié l'intégration,
 je me heurte à un message "Error: Ce token ne permet pas d'accéder au PRM". Le numéro de PRM est le bon, la procédure du token se passe bien (je l'ai refaite ce matin avec génération d'un nouveau token) via Enedis. Rien n'y fait... Une idée du problème ?
Merci, 
Jean-noël

![Capture d’écran 2024-02-12 à 08 34 31](https://github.com/bokub/conso-api/assets/32063109/046efc91-1506-4c49-af17-0f6d0f2b5c4b)

**Comment by bokub** [comment]
Hello !

C'est quoi ces gros trous ? T'aurais pas mis plein d'espaces dans ton numéro de PRM ?

![image](https://github.com/bokub/conso-api/assets/17952318/aaff6a61-e7a8-4163-894c-70ff8ed5083c)

**Comment by JNoVernay** [comment]
Aïe, oui, un copier/coller malheureux... Un grand merci.

**Comment by fouz37** [comment]
![enedis](https://github.com/bokub/conso-api/assets/152869360/c0fdedab-e832-4972-84de-e5bb869dd7f3)

Bonjour,

je ne trouve pas le token sur enedis .
J'ai essayé ses 2 clefs. token invalide
J'ai aussi essayé le clé relative acces donnees recu par sms : token invalide

**Comment by bokub** [comment]
@fouz37 Je sais pas ce que t'es en train de bidouiller mais en quoi ça concerne cette issue ? Et quel rapport avec Conso API ?
