### ISSUE TITLE
Authentification sur le compte professionnel d'Enedis

### ISSUE THREAD

**Issue by kewix** [bokub/conso-api#38]
Est-ce possible d'avoir une authentification non pas sur le compte particulier mais le compte professionnel d'Enedis ? 

A savoir https://mon-compte-professionnel.enedis.fr/donnees/ et non https://mon-compte-particulier.enedis.fr/donnees/ ? 

Je ne sais pas comment générer ce lien d'authentification ni même si conso-api est compatible ?

Merci !

**Comment by bokub** [comment]
Salut,

Pas sûr que ce soit possible.

En effet, voilà ce qu'on peut lire dans la documentation: 

![image](https://user-images.githubusercontent.com/17952318/126323559-f24ee3c9-5a9d-43e1-be91-857d8e3ae12a.png)

**Comment by claudeLimonin** [comment]
Il est tout à fait possible de récupérer les données de l’entreprise, mais le workflow est différent.  Toute la gestion du recueil des autorisations, de la gestion du consentement, etc., doit être traitée en interne et non par l’interface (voir SGE-TIERS).

**Comment by bokub** [comment]
Oui, en effet c'est possible techniquement, mais **pas** en passant par Conso API, qui est un wrapper de l'API "data connect" d'Enedis

![Screenshot_20260126-074517~2.png](https://github.com/user-attachments/assets/9ccf8f16-58bb-40b8-8fa5-7da0a2d20e62)

SGE est une autre plateforme à laquelle je n'ai pas accès.
