### ISSUE TITLE
erreur  "The Enedis API returned an error" et lien non visible sur compte Enedis

### ISSUE THREAD

**Issue by gpion** [bokub/conso-api#41]
Bonjour
J'ai suivi les instructions pour activer le partage des données.
J'ai récupéré le token.
Mais sur [la page de test](https://conso.boris.sh/exemples) ça échoue avec l'erreur "The Enedis API returned an error"
En outre sur la section Gérer l’accès à mes données => partage des données de mon compte Enedis (https://mon-compte-particulier.enedis.fr/donnees/)  Conso API n'est pas dans la liste
J'ai loupé une étape ?

**Comment by bokub** [comment]
Tu as le même problème que  #16 ?

**Comment by gpion** [comment]
> Tu as le même problème que  #16 ?

Ah oui en effet. J'ai du mal chercher.
Je m'abonne à l'autre ticket alors
Reste que c'est ennuyeux, pas de solution apparemment

**Comment by gpion** [comment]
L'erreur a disparu!
