### ISSUE TITLE
compte Enedis professionnel

### ISSUE THREAD

**Issue by Niconick99** [bokub/conso-api#54]
Bonjour, 
J'ai un compte ENEDIS professionnel. L'url est de type "https://mon-compte-professionnel.enedis.fr/..."
J'essai de connecter aux données de Conso API avec le module [@bokub/linky],
Le Conso-API envoi sur "https://mon-compte-particulier.enedis.fr/...", et je ne peux pas rajouter mon compteur pro.
Y a-t-il une manière de faire?
Merci

**Comment by bokub** [comment]
Hello @Niconick99 

Comme expliqué dans #38 , non ce n'est pas possible car l'API d'Enedis ne le permet pas.

Désolé !

**Comment by Niconick99** [comment]
merci @bokub pour cette réponse rapide!
Je sens que je vais devoir me lancer dans le bricolage d'un capteur TIC pour accéder à mes données... ;-(

**Comment by bokub** [comment]
Tu auras accès à des données temps réel au lieu d'attendre le lendemain, donc vois-le comme une opportunité :slightly_smiling_face:
