### ISSUE TITLE
API Enedis - Erreur 500.

### ISSUE THREAD

**Issue by HerveG45** [bokub/conso-api#56]
Bonjour,

API Enedis, erreur 500 depuis le 19/07.

Ci-dessous message d'erreur :

[19/07 06:41] Synchronization started for consumption data
Last saved statistic date is 17/07/2024
Cannot fetch consumption load curve from 2024-07-18 to 2024-07-19, here is the error:
Conso API a répondu avec une erreur
Code: 500
Réponse : {
    "status": 500,
    "message": "The Enedis API returned an error",
    "error": {
        "error": "technical_error",
        "error_description": "Technical error. Please try later."
    }
}
Data import returned nothing !
Connection with Home Assistant closed
Connection with Home Assistant established

**Comment by bokub** [comment]
Salut,

Si Enedis rencontre une erreur technique je ne peux rien y faire et vous non plus, il va falloir être patient.

Plus de pistes dans cette issue: https://github.com/bokub/ha-linky/issues/44

**Comment by HerveG45** [comment]
Et oui, il n'y a pas le choix, il va falloir attendre. Mais apparemment on n'est pas tous logés à la même enseigne, ça remonte parfaitement sur Beem !

Bonne fin de week-end !

![IMG_0716 - Copie](https://github.com/user-attachments/assets/74800978-a98e-4277-8650-acbd05bc1207)
