### ISSUE TITLE
Auth Enedis KO?

### ISSUE THREAD

**Issue by ClementPrimot** [bokub/conso-api#6]
Hello!

Il semblerait que l'authentification Enedis sur conso.boris.sh soit KO.
Lors d'un clic sur le bouton d'authentification, Enedis retourne une erreur 404.

Les tokens précédement générés semble ne plus fonctionner.

Enedis qui serait en vrac?

Cordialement.

**Comment by bokub** [comment]
C'est en effet Enedis qui est en vrac.
Je t'invite à réessayer une fois par jour, ça peut durer longtemps

Bonne journée !

**Comment by bokub** [comment]
Hello,
Le consentement est réparé !
