### ISSUE TITLE
Erreur 500 API

### ISSUE THREAD

**Issue by DieuGinette** [bokub/conso-api#60]
Bien le bonjour

L'API subit elle un problème technique actuellement ?

Voici mon erreur 
```javascript 
Date de la veille : 2024-09-23
Erreur dans la réponse de l'API : {
  status: 500,
  message: 'The Enedis API returned an error',
  error: {
    error: 'technical_error',
    error_description: 'Technical error. Please try later.'
  }
}
Statut : 500  

```

Voici la requete api qui est fait : (Image ci-joint)

![Capture](https://github.com/user-attachments/assets/a685064a-9740-4370-9b82-9f2da7a7ec01)

Je vous remercie

**Comment by bokub** [comment]
Bonjour,
Je ne travaille pas chez Enedis donc je n'ai aucune idée de si leur l'API subit un problème ou non

En attendant, le code m'a l'air bon, je confirme que le souci vient de chez Enedis

**Comment by bokub** [comment]
Peut-être que #16 est liée d'ailleurs

**Comment by DieuGinette** [comment]
Bonjour

Merci pour les réponses. Le problème était bien la date

En vous remerciant
