### ISSUE TITLE
Compteur incompatible - Octobre 2024

### ISSUE THREAD

**Issue by Ayno74** [bokub/conso-api#62]
Salut,

je rencontre un problème avec la demande de partage des données avec l'API. 

Le message "Compteur incompatible - Il doit collecter les données listées ci-dessus" s'affiche sur le site de Enedis. 

je souhaite utiliser l'API avec Node-Red ou HA.

**Comment by Lunyyx** [comment]
Bonjour,

J'ai exactement le même problème... J'ai vu que c'était arrivé dans le passé mais que ça avait été réglé... Nous sommes arrivés au mauvais moment ?

**Comment by billietl** [comment]
Bonjour,

de ce que j'ai pu lire, ça ressemble bien à #26... @bokub je me permet un ping, est-ce que c'est (encore une fois) enedis qui a un soucis ?

**Comment by Ayno74** [comment]
J'ai contacté le service Open Data de Enedis en parallèle de l'issue. 

Je tiendrais informer ce thread si j'ai des nouvelles.

**Comment by bokub** [comment]
Bonjour à tous,
Désolé pour le temps de réponse, ça ressemble malheureusement à #26, ce qui veut dire qu'il n'y a rien à faire à part attendre qu'Enedis réagisse.

Bonne nouvelle: d'autres services similaires sont concernés, donc Enedis a probablement déjà été informé plusieurs fois (en plus de l'email de @Ayno74)

J'enverrai moi aussi un e-mail dans quelques jours si le problème subsiste

Bonne soirée à tous !

**Comment by acemtp** [comment]
bon bah pareil que vous... l'oauth marche pas

**Comment by Ayno74** [comment]
Une personne de l'équipe du support API m'a répondu pour dire qu'ils ont ouvert un dossier et qu'un incident était déjà en cours d'analyse sur ce sujet. (mail reçu le 10/10 à 15h)

Je reviendrai donner des nouvelles.

**Comment by nivek1612** [comment]
j'ai le même problème. Les données sont transmises à EDF mais je ne peux pas obtenir un nouveau jeton

**Comment by bokub** [comment]
@jcdidier @nivek1612

Tout le monde a ce problème, si chaque utilisateur commente pour donner une information qu'on connait déjà ça ne sert à rien en plus de spammer tout le monde

**Comment by JPR-GitHub** [comment]
Bonjour à tous. @bokub : doit on attendre (pas grave) ou écrire à ENEDIS ? Merci d'avance

**Comment by Let000** [comment]
Salut, j'ai contacté ENEDIS il ne savent même pas de quoi je parle....

**Comment by Ayno74** [comment]
@Let000 

1] Je pense qu'il n'est plus utile de contacter Enedis pour ce problème qui, vraisemblablement, est bien au courant. 
2] Enedis regorge de services. En l'occurrence, celui de OPENDATA ou serviceclient-api qui répondent à ces questions. 
3] Si, visiblement Enedis, ou le service concerné, sont bien au courant. Le mail de réponse que j'ai reçu en est la preuve. 
4] Le problème est en cours de résolution, la seule chose qui est de mise est la patience dans un délai raisonnable. (Pas nécessaire de contextualiser votre problème dans ce thread qui est similaire à celui recensé)
5] Si vous remontez le fil, vous verrez que j'ai tenu informé le thread et je continuerai à le faire si j'ai des nouvelles. 

A ce jour la situation est au point mort depuis mon poste du 11 octobre. 

Bien à vous.

**Comment by Ayno74** [comment]
« Bonjour,
 
Nous sommes désolés, mais les analyses sont toujours en cours côté DSI.
 
Nous n’avons pas de retour pour le moment, dès que ce sera le cas nous reviendrons vers vous.
 
Nous vous présentons nos excuses pour la gêne occasionnée, et restons à votre écoute pour tout échange. »

mail reçu aujourd’hui à 16h10.

**Comment by momo7603** [comment]
Bonjour,

j'ai le même souci. J'écris non pas pour spammer, mais pour ajouter une information. Je ne sais pas si c'est pertinent, mais en plus du message d'incompatibilité, j'avais voulu changer la puissance souscrite (de 6 à 9 kVA). Normalement, cela coûte 3,70 € car c'est fait à distance sur le Linky. Or, mon fournisseur d'électricité me parlait de 42 € ! En gros, il fallait faire venir quelqu'un sur place, alors que mon fournisseur mentionnait bien 3,70 € aussi, mais pour moi, j'étais obligé de faire venir quelqu'un... C'est bizarre.

Du coup, je me pose les questions suivantes :

Je suis en HLM, donc ils ont installé les compteurs à la chaîne. Peut-être qu'ils ne sont pas configurés de la même manière que ceux des maisons individuelles ?
Je viens juste d'utiliser le formulaire de contact d'Enedis pour leur demander le changement de puissance (alors que normalement, il faut contacter le fournisseur d'électricité, qui lui, contacte Enedis). Dans mon message, j'ai demandé s'il y avait un problème avec mon Linky, et en 10 minutes, j'ai rafraîchi la page de mon compte Enedis, et ma puissance avait été passée à 9 kVA !
Êtes-vous dans un cas similaire au mien, en immeuble avec plusieurs Linky par palier ?

**Comment by Chris6729** [comment]
Bonjour moi en maison individuelle et même pb

**Comment by Ayno74** [comment]
Bonjour,

Pour la énième fois. Il n'est pas nécessaire de signaler que vous avez le même problème. Car beaucoup de monde est concerné pas ceci, voir même tout le monde qui souhaite interroger des API en lien avec Enedis. En effet, si vous effectuez une recherche vous trouverez que d'autres API sont concernés comme celle de Jeedom (un poste a été fait le 28/10 sur le forum concerné). Ceci à l'air d'intervenir sur des personnes voulant lier un nouveau compteur ou même sur des personnes ayant déjà lié leur compteur. 

Pour ceux qui souhaitent suivre le thread, un bouton existe sur la droite pour demander à être notifié en souscrivant. 

Ceux cherchant encore une solution sachez qu'il en existe deux : 
1- Utiliser le port TIC du compteur Linky
2- Patienter. 

Ce n'est pas contre l'API de bokub ou toute les API existante, mais si Enedis a des instabilités, même après correction, ça ne répondra pas à mon besoin.

**Comment by Chris6729** [comment]
Bonjour 
Pour ma part je répondais simplement à une question...quelque part c est l intérêt des forums
L instabilité d enedis j y crois pas trop car que ce soit avec hellowatt ou si je change de fournisseur Elec j ai bien la remontée de données et la demande de transmission se fait de suite
Je pense qu enedis bloque volontairement pourquoi? J en ai aucune idée mais je vois mal un opérateur attendre des mois pour savoir combien l usager consomme
C est dommage et frustrant d autant plus que bokub a fait du bon boulot....

**Comment by Ayno74** [comment]
@Chris6729 

Je parle d'instabilité parce que c'est déjà arrivé. Des issues similaires avec l'API de bokub ont déjà été lancée. De plus, sur d'autres forum, avec d'autres utilisateurs utilisant d'autres API pour Jeedom, eedomus, etc ont déjà rencontré ce soucis. 
Un point convergeant : Enedis et son service-client api. 
Donc si, tout porte à croire qu'Enedis est responsable (de façon volontaire ou non, ça personne ne peut savoir) et semble être le seul à pouvoir corriger.

Délibérément ou non, la récupération des données devient impossible et ce de manière longue (Plus d'1 mois depuis mon premier contact avec le service concerné). Je ne vois pas non les intérêts qu'ils auraient à faire cela. 

Effectivement, sur mon espace abonné, total energie à l'air de pouvoir récupéré les données. 
Passe t-il par la même API? Payent-ils un service pour cela?

**Comment by ouioui2821** [comment]
Bonjour, je voulais coupler mon compteur, mais pour moi aucun message compteur incompatible, mais juste une page vide. Est ce que c'est pareil pour vous? 
![image](https://github.com/user-attachments/assets/ffe2725d-cba2-4289-8b7c-35e36567ef53)

**Comment by zaibakker** [comment]
> oui. J'ai ouvert un incident auprès d'enedis pour voir meme si je ne crois pas un instant a une réponse de leur part.

Retour d'Enedis sur mon ticket: cela ne vient pas de mon compteur. mais plutot de consoAPI.
Elle m'a orientée sur la recuperation des stats par moi meme en branchant un équipement like 'lixee'.
Ca reste une alternative que je connaissais mais je souhaitais essayer consoAPI. Je me donne encore un peu de tps pour faire mon choix.

Force et courage au dev pour résoudre le pb. ❤️

**Comment by dpobel** [comment]
:tada: ça vient de tomber en marche pour moi !

**Comment by Adam-Said** [comment]
> 🎉 ça vient de tomber en marche pour moi !

Idem pour moi ! 🎉

**Comment by olivierlambert** [comment]
Tout pareil, c'est fonctionnel depuis ces 2 dernière heures !

**Comment by WelsyMC** [comment]
Yes profitez en, je confirme, j'attendais depuis fin septembre... 
Faudrait :heavy_check_mark: l'issue si ça peut ping du monde !

**Comment by ouioui2821** [comment]
Bonjour, idem pour moi ça fonctionne et même très bien top.

**Comment by Pops122** [comment]
Bonjour,
Cela fonctionne ! Au top.
Juste une question : ds HA, j'ai bien récupéré l'historique de mon linky consommation mais pas celui du linky production. Je n'ai récupéré que 1 semaine. Une manip spéciale à faire ? :-)

**Comment by olivierlambert** [comment]
Même constat que @Pops122 ici

**Comment by bokub** [comment]
En effet, le problème est bel est bien résolu ! :partying_face: 

Temps de résolution de la part d'Enedis: **43 jours**

**Comment by nivek1612** [comment]
Cela fonctionne bien maintenant. Si vous aimez suivre les coûts et l'utilisation et que, comme moi (client EDF), vous avez une charge annuelle ainsi qu'une unité de frais en kWh. Il existe un moyen de l'afficher dans le tableau de bord énergétique en l'allouant quotidiennement comme ceci. Si cela vous intéresse, je le partagerai dans un autre fil de discussion.
![IMG_5803](https://github.com/user-attachments/assets/2a6b6872-2712-45d7-ac75-71f0f78508f0)

**Comment by Noob38130** [comment]
Bonjour,

Je vois que le service est opérationnel chez vous mais je viens de tenter d'obtenir un token et je tombe sur la page ENEDIs suivante. Le'accès est de nouveau bloqué ?
![image](https://github.com/user-attachments/assets/dc77f3d8-ddff-4c8f-81c9-9cb3970b783f)

**Comment by valentinpx** [comment]
Hello, j'ai reçu un appel d'Enedis hier, le problème est (à nouveau) résolu

**Comment by Nardol** [comment]
Désolé pour le déterrage mais il semble que ça recommence. D'autres ont-il le problème ?

**Comment by Geroumy** [comment]
yes pareil, lié à ça https://opendata.enedis.fr/pages/changement ? @bokub es-tu au courant ?

**Comment by bokub** [comment]
@Geroumy Merci mais je ne pense pas que ce soit lié, les "Open data" ce sont les données ouvertes accessibles à tous (donc pas la consommation individuelle de chaque compteur)

**Comment by Nardol** [comment]
ça refonctionne, j'ai pu obtenir mon token
