### ISSUE TITLE
Récupération de token

### ISSUE THREAD

**Issue by JulienDidier-PNS** [bokub/conso-api#63]
J'ai déjà effectué le partage de données mais j'ai perdu mon token... En voulant faire une clean install de mon client HA, je n'avais pas noté mon token. Est-il possible d'en générer un nouveau ?

**Comment by gstlanglois** [comment]
Bonjour, je confirme toujours impossible d'obtenir un token : 

![image](https://github.com/user-attachments/assets/caf907ee-59e8-4f14-a6a4-e2769d410003)

**Comment by Nosnahc** [comment]
idem pour moi :'(

**Comment by odauguet** [comment]
Bonjour, idem pour moi et Enedis ne semble pas dire que ca se fait chez eux. Si quelqu'un voit la page se modifier pour pouvoir le faire, n'hésitez pas à partager. Merci

**Comment by makak06** [comment]
Hello
Même probleme ici il semblerait...
J'ai une page blanche avec uniquement le titre : Partage de vos données d'electricité.
Du coup pas de token :-(

**Comment by bokub** [comment]
Hello,

- Au risque de me répéter, l'issue existe déjà dans #62
- Tout le monde a le même problème
- Commenter "j'ai le même problème" n'apporte rien à la conversation mais envoie un e-mail à tous les participants.

Je me permets de fermer cette issue qui est un doublon.
