### ISSUE TITLE
Conso api, site web enedis

### ISSUE THREAD

**Issue by User969696** [bokub/conso-api#68]
Bonjour,

Suis-je le seul à essayer de générer un token, m'authentifier, et obtenir une page blanche sur Enedis ?
J'ai essayé avec Firefox, Edge, et Chrome : même résultat.
![00](https://github.com/user-attachments/assets/3bc02007-ddb5-40c3-9385-b86396b9166c)

**Comment by bokub** [comment]
#62

**Comment by bokub** [comment]
Hello, visiblement l'écran d'Enedis est encore plus cassé que d'habitude, mais ton issue est la même que #62
