### ISSUE TITLE
Problème d'acquisition de token 

### ISSUE THREAD

**Issue by J3a90r** [bokub/conso-api#70]
Bonjour,

Merci beaucoup pour ce travail.

J'ai, pour ma part, un problème pour générer le token. 

Le partage est activé sur enedis, mais a l'utilisation de conso api, rien...
![Screenshot_20241116-155703](https://github.com/user-attachments/assets/2068a48e-24c2-4b29-a0f1-4bcbf64a723b)

J'ai essayé plusieurs navigateurs plus terminaux.

Pouvez vous m'aiguiller sur ce que je fais de travers.

Merci beaucoup 👍

**Comment by bokub** [comment]
Doublon avec #62
