### ISSUE TITLE
Erreur 404 sue enedis

### ISSUE THREAD

**Issue by AlainGrenot** [bokub/conso-api#8]
Bonjour Boris
Tout d'abord merci pour nous faciliter la tâche. Je suis assez néophyte en domotique mais t'es explications sont très claires. 
J ai un soucis avec  enedis car en suivant le lien que tu nous indiques, l'appli me renvoie erreur 404. 
Pourtant la récupération des données tant consommateur que producteur sont activees
Ai je rate une étape. 

Merci par avance de To aide
Cordialement

**Comment by bokub** [comment]
Salut !
Même réponse que pour #6 et #7 : c'est pareil pour tout le monde et je ne peux rien y faire, je t'invite à t'armer de patience

Bonne soirée

**Comment by bokub** [comment]
Hello,
Le consentement est réparé !
