### ISSUE TITLE
No consent can be found for this customer and this usage point.

### ISSUE THREAD

**Issue by bil44** [bokub/conso-api#9]
Bonjour,
Enfin, J'ai réussi à avoir mon token hier,  super !
Malgré cela, lors de la récupération de la prod,  via ,  https://conso.boris.sh/exemples, ou, directement de mon repo local, j'ai la même erreur :
```
root@JeedomAtlas:/home/bil# ./linky daily
Conso API a répondu avec une erreur
Code : 403
Réponse : {
    "status": 403,
    "message": "The Enedis API returned an error",
    "error": {
        "error": "ADAM-DC-0008",
        "error_description": "No consent can be found for this customer and this usage point."
    }
}
```
Via le site web  https://conso.boris.sh/exemples (dans le curl , j'ai masqué une partie de mon PRM est remplacé le token par monToken  
```
curl -X GET \
    'https://conso.boris.sh/api/daily_consumption?prm=xxxxxxx0133&start=2023-09-19&end=2023-09-22' \
    -H 'Authorization: Bearer monToken'
```
Je suis impatient?  faut-il attendre plus de 24h entre l’acquisition du token et son utilisation ? ou il y a un pb?

D'avance merci pour ton aide

**Comment by bokub** [comment]
Oui il y a un problème, Enedis ne retrouve pas la trace de ton consentement... Vu comme ils sont en galère c'est pas impossible que leur serveur ait planté à un moment et n'ait pas réussi à bien l'enregistrer

Est-ce que tu peux réessayer de créer un token en prenant soin de ne cocher **que** le PRM concerné ? Normalement tu peux l'utiliser dès la fin du consentement y'a aucun délai

**Comment by bokub** [comment]
Je viens de tester avec mon compte et aucun problème... 

Je t'invite à réessayer plusieurs fois la semaine prochaine et me dire si c'est toujours cassé vendredi prochain !

**Comment by bil44** [comment]
Merci, de ton retour, je te tiens au courant.

**Comment by bil44** [comment]
Bonjour,
Après une semaine, je viens de refaire avec un nouveau token, toujours la même erreur :
```
{  "status": 403,  "message": "The Enedis API returned an error",  "error": {    "error": "ADAM-DC-0008",    "error_description": "No consent can be found for this customer and this usage point."  }}
```

**Comment by bil44** [comment]
Bonjour,
Pour information, j'ai utilisé un autre service https://www.bdpv.fr pour accéder  à mes données , et ça fonctionne bien, le consentement est OK, et la récupération des datas est OK.
Pour info , c'est de la production.
Si cela peut aider.
Cordialement

**Comment by bokub** [comment]
Sorry mais non ça m'aide pas, tu es le seul utilisateur qui m'a remonté le problème et pour tous les autres ça marche, donc je t'avoue que j'ai pas plus de temps que ça à y consacrer

**Comment by PATGAR64** [comment]
@bil44, bonjour.
Depuis que j'ai ajouté ds HA la conf pour ajouter mes index de production j'ai la même erreur que toi Error 403 ADAM-DC-0008 a la fois sur Conso-api et l'addon ha-linky de bokub. Avait tu pu trouver une soluce à ton époque ?
J'ai essayé plusieurs démarches pour comprendre mais sans résultat.
Patrick

**Comment by bil44** [comment]
Bonjour Patrick,
Désolé, c'est très loin (plus de deux ans), je ne me rappelle plus et depuis, j'ai modifié ma façon d'utiliser l'API.
Peut être juste un problème de consentement sur ton compte ENEDIS ?!
Actuellement, HA-Linky  (je traque la Production uniquement) marche bien.
Je te conseille d'ouvrir un nouveau sujet pour que bokub puisse t'aider.
Bonne chance
Cordialement
Bil
